### ISSUE TITLE
Diff keeps regenerating foreign key constrains and indexes

### ISSUE THREAD

**Issue by tadas-subonis** [liquibase/liquibase-hibernate#129]
Whenever I run diff with hibernate it adds to a changelog a bunch of drop and add foreign key statements even though the keys are present there.

I am using hibernate 5.0.9 and SQL Server 2012

Statements look like these:
```
    <changeSet author="Tadas (generated)" id="1475664734661-15">
        <dropForeignKeyConstraint baseTableName="Item" constraintName="FKth5y70agjmvf2h0d3cfucfaum"/>
        <addForeignKeyConstraint baseColumnNames="user_id" baseTableName="Item" constraintName="FKth5y70agjmvf2h0d3cfucfaum" referencedColumnNames="id" referencedTableName="User"/>
    </changeSet>
    <changeSet author="Tadas (generated)" id="1475664734661-16">
        <dropIndex indexName="IDXmb7t3wdwcmahd48kop849rnk5" tableName="AccessToken"/>
        <createIndex indexName="IDXmb7t3wdwcmahd48kop849rnk5" tableName="AccessToken">
            <column name="userId"/>
        </createIndex>
    </changeSet>
```

basically it drops all indexes and adds them again and I don't really see a purpose here.

**Comment by nvoxland** [comment]
Can you try with the changes I pushed?

**Comment by tadas-subonis** [comment]
It seems that there is no more excesive foreign key constrain generation but an Index that I've manually added with @Index annotation was still recreated.

**Comment by robertoschwald** [comment]
Same here with 3.6 (Hibernate4). 
Existing index is always re-created:

Grails Entity:

```groovy
class UserRole implements Serializable {
	private static final long serialVersionUID = 1

	User user
	Role role

	static mapping = {
		cache true
		id composite:['role', 'user']
		version false
	}
}
```

Always leads to this diffs generated:

```groovy
databaseChangeLog = {

    changeSet(author: "rob (generated)", id: "1477901616435-1") {
        dropIndex(indexName: "FK_4tjo7nu3mr9j4b7pp0bt4ur3m", tableName: "user_role_eo")
    }

    changeSet(author: "rob (generated)", id: "1477901616435-2") {
        dropForeignKeyConstraint(baseTableName: "user_role_eo", constraintName: "FK_4tjo7nu3mr9j4b7pp0bt4ur3m")

        addForeignKeyConstraint(baseColumnNames: "user_da_id", baseTableName: "user_role_eo", constraintName: "FK_4tjo7nu3mr9j4b7pp0bt4ur3m", referencedColumnNames: "id_da", referencedTableName: "user_eo")
    }

    changeSet(author: "rob (generated)", id: "1477901616435-3") {
        dropForeignKeyConstraint(baseTableName: "user_role_eo", constraintName: "FK_f71rit4ced3vswl68lil7xhii")

        addForeignKeyConstraint(baseColumnNames: "role_da_id", baseTableName: "user_role_eo", constraintName: "FK_f71rit4ced3vswl68lil7xhii", referencedColumnNames: "id_da", referencedTableName: "role_eo")
    }
}
```

**Comment by edwardotis** [comment]
Hi @nvoxland, 

We are experiencing a similar problem with the hibernate4. 
As you fixed this for hibernate 5, could you investigate if there is a similar fix for hibernate 4?

https://github.com/liquibase/liquibase-hibernate/issues/134
https://github.com/liquibase/liquibase-hibernate/issues/136

Thanks!

**Comment by TechGamer0** [comment]
I still have the same issue, I am using liquibase-hibernate5:3.6 version and Oracle.

**Comment by Bert-R** [comment]
Indeed, I just upgraded to 3.7 and still have that issue. Against an up-to-date database of [this project](yonadev/yona-server), I get this changelog:

```
databaseChangeLog:
- changeSet:
    id: 1557163501638-1
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activities
        constraintName: FK153j79bacpdr3xya2m2mcugqm
- changeSet:
    id: 1557163501638-2
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users
        constraintName: FK1q62ir796usoi0lxdifxbtjuw
- changeSet:
    id: 1557163501638-3
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: devices_anonymized
        constraintName: FK1uuw0bpvp264yaasbb8i1et48
- changeSet:
    id: 1557163501638-4
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users
        constraintName: FK248gal67yr0x10v3c91jhukxn
- changeSet:
    id: 1557163501638-5
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: interval_activities
        constraintName: FK2g9g82nxkn0q3fmkic8ghkm50
- changeSet:
    id: 1557163501638-6
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: user_devices
        constraintName: FK396p3k1wh84ywuihnx0yyq3le
- changeSet:
    id: 1557163501638-7
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FK3frmw5yf1s2r4qhk3fh5j1kcv
- changeSet:
    id: 1557163501638-8
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activities
        constraintName: FK4ffka0h8fl6po1qxmjb6rwbw0
- changeSet:
    id: 1557163501638-9
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activity_category_localizable_description
        constraintName: FK4qhwlsehrr71sjwsa0mogu9e0
- changeSet:
    id: 1557163501638-10
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: buddies_anonymized
        constraintName: FK4svk59nnt43qju5b152xu0t9l
- changeSet:
    id: 1557163501638-11
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activity_category_applications
        constraintName: FK5g852ju03p65ow1i6mpvd3olf
- changeSet:
    id: 1557163501638-12
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FK6mk4xuvoujd64qglc7kcqx92a
- changeSet:
    id: 1557163501638-13
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users
        constraintName: FK6t6in5chnm4ho3akt1c9u2e58
- changeSet:
    id: 1557163501638-14
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activities
        constraintName: FK747bf883p2vj21ct2sak46qws
- changeSet:
    id: 1557163501638-15
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users
        constraintName: FK7vrelocmqfxunluioscp8w90l
- changeSet:
    id: 1557163501638-16
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: goals
        constraintName: FK8t3kpuahr7c37x0pvrntgh5le
- changeSet:
    id: 1557163501638-17
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: message_sources
        constraintName: FK8utei8orw9jeertnjipmf5iyg
- changeSet:
    id: 1557163501638-18
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: vpn_status_change_events
        constraintName: FK8uxpqc3d3utrwomxmwj0xf8jr
- changeSet:
    id: 1557163501638-19
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: interval_activities
        constraintName: FK9i8wm0mvbpijk76slyeaxcxmg
- changeSet:
    id: 1557163501638-20
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FK9owuqxu4u0ur5yykbvto7oyr9
- changeSet:
    id: 1557163501638-21
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: interval_activities
        constraintName: FK9rb76feje8jaw7tmh0efmtlvu
- changeSet:
    id: 1557163501638-22
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users
        constraintName: FKa2nxdfj6f99odw541q583m26x
- changeSet:
    id: 1557163501638-23
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKb10e1tvcp849tqtak8x9mlqmx
- changeSet:
    id: 1557163501638-24
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKca68vwrjfljvrm4c72dqtn51r
- changeSet:
    id: 1557163501638-25
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKdqnlq2invx8yykla2f131w8qx
- changeSet:
    id: 1557163501638-26
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKe1nv0ek0llio3tkc7iyhnyey6
- changeSet:
    id: 1557163501638-27
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKeppihqh1ll3o7nipx3a0eh0pp
- changeSet:
    id: 1557163501638-28
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: goals
        constraintName: FKf6c36360ciqp8hbmf5dr3j4sx
- changeSet:
    id: 1557163501638-29
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users
        constraintName: FKggiyvtbxt879s73jlfyq78km5
- changeSet:
    id: 1557163501638-30
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKgl2kca1cjxtq09b7b4i31hrx
- changeSet:
    id: 1557163501638-31
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: users_anonymized
        constraintName: FKhk9ynujqvsey0cq2641n3obmr
- changeSet:
    id: 1557163501638-32
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: buddy_devices
        constraintName: FKhue14dflrmi0xfot2jojcgiiv
- changeSet:
    id: 1557163501638-33
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activity_category_smoothwall_categories
        constraintName: FKjqgrvhqyx0gjoypx0wpt4sv0n
- changeSet:
    id: 1557163501638-34
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: activity_category_localizable_name
        constraintName: FKk7fmyohup5axqu1gkgny0qqom
- changeSet:
    id: 1557163501638-35
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKm67ayo2a6tt1oytb7mhw708ye
- changeSet:
    id: 1557163501638-36
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: goals
        constraintName: FKnr2tjc55ltfutjch3dbek11dr
- changeSet:
    id: 1557163501638-37
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: buddies
        constraintName: FKq3lbn4hfhp74s01ww7hnc17cm
- changeSet:
    id: 1557163501638-38
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: messages
        constraintName: FKt3di87vj0cvcyx8c6hycr8yg8
- changeSet:
    id: 1557163501638-39
    author: Bert (generated)
    changes:
    - dropUniqueConstraint:
        constraintName: UC_USERSMOBILE_NUMBER_COL
        tableName: users
- changeSet:
    id: 1557163501638-40
    author: Bert (generated)
    changes:
    - dropUniqueConstraint:
        constraintName: UC_WHITE_LISTED_NUMBERMOBILE_NUMBER_COL
        tableName: white_listed_number
- changeSet:
    id: 1557163501638-41
    author: Bert (generated)
    changes:
    - dropUniqueConstraint:
        constraintName: no_duplicate_activities
        tableName: interval_activities
- changeSet:
    id: 1557163501638-42
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: activities
- changeSet:
    id: 1557163501638-43
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: activity_categories
- changeSet:
    id: 1557163501638-44
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: activity_category_applications
- changeSet:
    id: 1557163501638-45
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: activity_category_localizable_description
- changeSet:
    id: 1557163501638-46
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: activity_category_localizable_name
- changeSet:
    id: 1557163501638-47
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: activity_category_smoothwall_categories
- changeSet:
    id: 1557163501638-48
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: buddies
- changeSet:
    id: 1557163501638-49
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: buddies_anonymized
- changeSet:
    id: 1557163501638-50
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: buddy_devices
- changeSet:
    id: 1557163501638-51
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: confirmation_codes
- changeSet:
    id: 1557163501638-52
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: devices_anonymized
- changeSet:
    id: 1557163501638-53
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: goals
- changeSet:
    id: 1557163501638-54
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: interval_activities
- changeSet:
    id: 1557163501638-55
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: message_destinations
- changeSet:
    id: 1557163501638-56
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: message_sources
- changeSet:
    id: 1557163501638-57
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: messages
- changeSet:
    id: 1557163501638-58
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: new_device_requests
- changeSet:
    id: 1557163501638-59
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: user_devices
- changeSet:
    id: 1557163501638-60
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: user_photo
- changeSet:
    id: 1557163501638-61
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: users
- changeSet:
    id: 1557163501638-62
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: users_anonymized
- changeSet:
    id: 1557163501638-63
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: users_private
- changeSet:
    id: 1557163501638-64
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: vpn_status_change_events
- changeSet:
    id: 1557163501638-65
    author: Bert (generated)
    changes:
    - dropTable:
        tableName: white_listed_number
```
